### ISSUE TITLE
Can't apply custom Mapbox style

### ISSUE THREAD

**Issue by bureauproto** [bouchenoiremarc/Sketch-Maps#2]
I alway get the message "Style not found" – Map is public, the URL is copied from Studio correctly. 
That's the style I'd like to apply (OPEC): mapbox://styles/filterfreak/cjh8wlaj228m22rln02v628tu

**Comment by bureauproto** [comment]
Nevermind! Seems to be a caching issue with Mapbox :)

**Comment by JaimeHolland88** [comment]
How did you fix your problem with Mapbox? I am having the same problem. When I paste my custom style URL from mapbox I get the error message from sketch : "The custom style URL appears to be invalid" . Any my URL is also public.
