### ISSUE TITLE
Enable latitude / longitude searches

### ISSUE THREAD

**Issue by monkian** [bouchenoiremarc/Sketch-Maps#3]
Hi, thanks for creating the plugin. It's really useful.
One thing that is limiting the use for me is that I HAVE to specify an address and cannot just enter latitude and longitude. This in no issue for locations in cities, but rather locations in rural areas or national parks that don't have an address. I would appreciate if you'd consider adding this feature. Thanks!
![screen shot 2018-12-17 at 10 46 17 am](https://user-images.githubusercontent.com/2484377/50060501-0dad9c00-01e9-11e9-9fd2-bb19031a6a26.png)

**Comment by marcbouchenoire** [comment]
Hi, thanks! That's a great suggestion, I'll work on that in the next few days.
